export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const ADD_PROJECT = 'ADD_PROJECT'
export const ADD_TASK = 'ADD_TASK'
export const ASSIGN_PROJECT = 'ASSIGN_PROJECT'
export const ASSIGN_TASK = 'ASSIGN_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_PROJECT = 'DELETE_PROJECT'
